#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

fi

echo "Remember to install mermaid support for nvim:"
echo ""
echo "npm install -g @mermaid-js/mermaid-cli"
echo ""
echo ""
echo "Remember to install Tmux Plugin Manager:"
echo ""
echo "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm"
echo ""
echo ""
echo "Remember to install safe-chain:"
echo "curl -fsSL https://github.com/AikidoSec/safe-chain/releases/latest/download/install-safe-chain.sh | sh"
